#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=false

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Kotlin/Native: allow configuring the project on non-Apple hosts (iOS targets just won't build here).
kotlin.native.ignoreDisabledTargets=true

#Android
android.useAndroidX=true
android.nonTransitiveRClass=true
